# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 17:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('VISA', 'VISA'), ('MasterCard', 'MasterCard'), ('American Express', 'American Express'), ('MEAL Card', 'MEAL Card')], max_length=100)),
                ('card_number', models.PositiveIntegerField(max_length=16)),
                ('cvv', models.PositiveIntegerField(max_length=3)),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, default='https://i.imgur.com/oo1xyTr.jpg', upload_to='static/profile')),
                ('phone_number', models.PositiveIntegerField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('about', models.TextField(blank=True, max_length=100, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pay.Account')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
