# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 09:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pay', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='account',
        ),
        migrations.AddField(
            model_name='account',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='qr_id',
            field=models.ImageField(blank=True, null=True, upload_to='static/profile'),
        ),
        migrations.AlterField(
            model_name='account',
            name='card_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='cvv',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
