# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0002_remove_profile_qr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='static/profile'),
        ),
    ]
