# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-01 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0004_auto_20181025_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='card_type',
            field=models.CharField(choices=[('VISA', 'VISA'), ('MasterCard', 'MasterCard'), ('American Express', 'American Express'), ('MEAL Card', 'MEAL Card'), ('M-Pesa', 'M-Pesa')], max_length=100),
        ),
    ]
