# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0004_auto_20181025_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='card_number',
            field=models.BigIntegerField(),
        ),
    ]
