# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-09 09:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('VISA', 'VISA'), ('MasterCard', 'MasterCard'), ('American Express', 'American Express'), ('MEAL Card', 'MEAL Card'), ('M-Pesa', 'M-Pesa')], max_length=100)),
                ('card_number', models.BigIntegerField()),
                ('cvv', models.PositiveIntegerField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
