# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-26 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_goodie_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodie',
            name='picture',
            field=models.ImageField(blank=True, upload_to='static/shop'),
        ),
    ]
