# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-08 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20181105_1111'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catalog',
            new_name='Category',
        ),
        migrations.AddField(
            model_name='goodie',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
